driver:
  name: ec2
  region: us-east-1
  require_chef_omnibus: true
  aws_ssh_key_id: jenkins
  availability_zone: us-east-1a
  require_chef_omnibus: true
  security_group_ids: ["sg-5f17af2b"]
  instance_type: t2.medium
  subnet_id: subnet-6d47ca42
  associate_public_ip: true
  interface: dns
  retryable_sleep: 10
  retryable_tries: 120

  winrm:
    boot_timeout: 600
    max_tries: 500
provisioner:
  name: chef_zero
  #always_update_cookbooks: true
  require_chef_omnibus: 13.1
  wait_for_retry: 120 #
  retry_on_exit_code:
    - 35

  max_retries: 100

  client_rb:
    exit_status: :enabled # Opt-in to the standardized exit codes
    #log_level: :debug
    #log_location: STDOUT
    #verbose_logging: true
verifier:
name: inspec

platforms:
  - name: windows-2012r2
    driver:
      image_id: ami-a64855dc
      tags:
        Name: test-kitchen-2012r2
    transport:
      elevated: true
      username: aeadmin
      password: @3@dm1n

suites:
  - name: default
    run_list:
      - recipe[ae-windows-base::reboot-handler]
      - recipe[ae-windows-base::chocolatey_packages]
      - recipe[ae-windows-base::set_local_account_token_filter_policy]
      - recipe[ae-windows-base-sqlserver::deactivate_uac]
      - recipe[ae-windows-base-sqlserver::default]
    attributes:
      ae-windows-base-chef:
        reboot_mode: reboot
    verifier:
      inspec_tests:
        - test/smoke/default
