driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  #log_level: :debug
  #log_location: STDOUT
  #verbose_logging: true
  retry_on_exit_code:
    - 35 # 35 is the exit code signaling that the node is rebooting

  max_retries: 5
  wait_for_retry: 120
  client_rb:
    exit_status: :enabled # Opt-in to the standardized exit codes
    client_fork: false  # Forked instances don't return the real exit code

platforms:

  - name: windows-2012r2
    driver_config:
      box: mwrock/Windows2012R2
 
    provisioner:
      require_chef_omnibus: true

suites:
  - name: default
    run_list:
      - recipe[ae-windows-base::reboot-handler]
      - recipe[ae-windows-base::ae-bginfo]
      - recipe[ae-windows-base::ae-wallpaper]
      - recipe[ae-windows-base::chocolatey_packages]   
      - recipe[ae-windows-base::install_ps_modules]
      - recipe[ae-windows-base::ae-manage-computer]
      - recipe[ae-windows-base::clean_sxs]
      - recipe[ae-windows-base::set_local_account_token_filter_policy]


      