---
driver:
  name: ec2
  region: us-east-1
  require_chef_omnibus: true
  aws_ssh_key_id: jenkins
  availability_zone: us-east-1a
  require_chef_omnibus: true
  security_group_ids: ["sg-5f17af2b"]
  instance_type: t2.medium
  subnet_id: subnet-6d47ca42
  associate_public_ip: true
  interface: dns
  retryable_sleep: 10
  retryable_tries: 60

  winrm:
    boot_timeout: 600
    max_tries: 500
provisioner:
  name: chef_zero
  #always_update_cookbooks: true
  require_chef_omnibus: true
  wait_for_retry: 60 #
  retry_on_exit_code:
    - [35, 1] #This allows for reboots

  max_retries: 100

  client_rb:
    exit_status: :enabled # Opt-in to the standardized exit codes
    client_fork: false  # Forked instances don't return the real exit code
    log_level: :debug
    log_location: STDOUT
    verbose_logging: true
verifier:
name: inspec

platforms:
  - name: windows-2012r2
    driver:
      image_id: ami-a64855dc
      tags:
        Name: test-kitchen-2012r2
    transport:
      elevated: true
      username: kitchen
      password: k1tch3n

suites:
  - name: default
    run_list:
      - recipe[ae-windows-base::reboot-handler]
      - recipe[ae-windows-base::chocolatey_packages]

    attributes:
      ae-windows-base-chef:
        reboot_mode: reboot
    verifier:
      inspec_tests:
        - test/smoke/default
