---
driver:
  name: ec2
  retryable_sleep: 10
  retryable_tries: 60

  winrm:
    boot_timeout: 600
    max_tries: 500
provisioner:
  name: chef_zero
  #always_update_cookbooks: true
  require_chef_omnibus: true
  wait_for_retry: 60 #
  retry_on_exit_code:
    - [35, 1] #This allows for reboots
 
  max_retries: 100

  client_rb:
    exit_status: :enabled # Opt-in to the standardized exit codes
    client_fork: false  # Forked instances don't return the real exit code
    log_level: :debug
    log_location: STDOUT
    verbose_logging: true

platforms:
  - name: windows-2012r2
    driver:
      tags:
        Name: test-kitchen-2012r2
    transport:
      elevated: true
      username: kitchen
      password: k1tch3n

suites:
  - name: default
    run_list:
      - recipe[ae-windows-base::reboot-handler]
      - recipe[ae-windows-base::chocolatey_packages]   
      - recipe[ae-windows-base::carbonblack]
      - recipe[ae-windows-base::install_ps_modules]
      - recipe[ae-windows-base::ae-manage-computer]
      - recipe[ae-windows-base::ae-mcafee]
      - recipe[ae-windows-base::clean_sxs]
      - recipe[ae-windows-base::set_local_account_token_filter_policy]

    attributes: